# Generated by Django 4.2.7 on 2025-09-15 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reconnaissance", "0001_initial"),
        ("scanning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconresult",
            name="scan_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recon_results",
                to="scanning.scansession",
            ),
        ),
        migrations.AddIndex(
            model_name="reconresult",
            index=models.Index(
                fields=["scan_session", "result_type"],
                name="recon_resul_scan_se_275144_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconresult",
            index=models.Index(
                fields=["discovered_asset"], name="recon_resul_discove_242abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconresult",
            index=models.Index(
                fields=["is_in_scope"], name="recon_resul_is_in_s_bfa226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconresult",
            index=models.Index(
                fields=["discovered_by_tool"], name="recon_resul_discove_2089ab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reconresult",
            unique_together={("scan_session", "discovered_asset", "result_type")},
        ),
    ]
