# Generated by Django 4.2.7 on 2025-09-15 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(
                        help_text="Name of the generated report", max_length=255
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Report"),
                            ("executive", "Executive Summary"),
                            ("bug_bounty", "Bug Bounty Report"),
                            ("compliance", "Compliance Report"),
                            ("custom", "Custom Report"),
                        ],
                        help_text="Type of report generated",
                        max_length=50,
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("markdown", "Markdown"),
                            ("docx", "Word Document"),
                        ],
                        default="pdf",
                        help_text="Output format of the report",
                        max_length=20,
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True, help_text="Executive summary for management"
                    ),
                ),
                (
                    "technical_details",
                    models.TextField(
                        blank=True, help_text="Technical details and methodology"
                    ),
                ),
                (
                    "methodology_used",
                    models.TextField(
                        blank=True, help_text="Testing methodology description"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Security recommendations"),
                ),
                (
                    "pdf_file_path",
                    models.FileField(
                        blank=True,
                        help_text="Path to PDF report file",
                        null=True,
                        upload_to="reports/pdf/",
                    ),
                ),
                (
                    "html_file_path",
                    models.FileField(
                        blank=True,
                        help_text="Path to HTML report file",
                        null=True,
                        upload_to="reports/html/",
                    ),
                ),
                (
                    "json_file_path",
                    models.FileField(
                        blank=True,
                        help_text="Path to JSON data export",
                        null=True,
                        upload_to="reports/json/",
                    ),
                ),
                (
                    "total_vulnerabilities_reported",
                    models.IntegerField(
                        default=0, help_text="Total vulnerabilities included in report"
                    ),
                ),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                (
                    "pii_redacted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether PII has been redacted from this report",
                    ),
                ),
                (
                    "redaction_rules_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="PII redaction rules that were applied",
                    ),
                ),
                (
                    "include_raw_data",
                    models.BooleanField(
                        default=False, help_text="Include raw tool outputs in report"
                    ),
                ),
                (
                    "include_screenshots",
                    models.BooleanField(
                        default=True, help_text="Include vulnerability screenshots"
                    ),
                ),
                (
                    "include_remediation",
                    models.BooleanField(
                        default=True, help_text="Include remediation recommendations"
                    ),
                ),
                (
                    "include_exploitation_chains",
                    models.BooleanField(
                        default=True, help_text="Include exploitation chain details"
                    ),
                ),
                (
                    "template_used",
                    models.CharField(
                        blank=True,
                        help_text="Report template that was used",
                        max_length=100,
                    ),
                ),
                (
                    "custom_styling",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom styling options applied",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.CharField(
                        default="AutoReporter",
                        help_text="System or user that generated the report",
                        max_length=100,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of generated report file in bytes",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Name of the report template",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Report"),
                            ("executive", "Executive Summary"),
                            ("bug_bounty", "Bug Bounty Report"),
                            ("compliance", "Compliance Report"),
                            ("custom", "Custom Report"),
                        ],
                        help_text="Type of reports this template is for",
                        max_length=50,
                    ),
                ),
                (
                    "template_content",
                    models.TextField(help_text="Jinja2 template content"),
                ),
                (
                    "css_styling",
                    models.TextField(
                        blank=True, help_text="CSS styles for the template"
                    ),
                ),
                (
                    "javascript_code",
                    models.TextField(
                        blank=True, help_text="JavaScript code for interactive elements"
                    ),
                ),
                (
                    "default_sections",
                    models.JSONField(
                        default=list, help_text="Default sections to include in reports"
                    ),
                ),
                (
                    "required_data_fields",
                    models.JSONField(
                        default=list, help_text="Required data fields for this template"
                    ),
                ),
                (
                    "optional_data_fields",
                    models.JSONField(
                        default=list, help_text="Optional data fields for this template"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for its type",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["template_name"],
                "indexes": [
                    models.Index(
                        fields=["template_type"], name="report_temp_templat_fe87ac_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="report_temp_is_acti_2cb562_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="report_temp_is_defa_fe1168_idx"
                    ),
                ],
            },
        ),
    ]
