# Generated by Django 4.2.7 on 2025-09-15 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reporting", "0001_initial"),
        ("scanning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="scan_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="scanning.scansession",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["scan_session", "report_type"],
                name="reports_scan_se_3f169f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_at"], name="reports_generat_a38578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="reports_report__ff8b25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["pii_redacted"], name="reports_pii_red_f7515d_idx"
            ),
        ),
    ]
